import Head from "next/head"
import styles from "../styles/Home.module.css"
import { GraphQLClient, gql } from "graphql-request"
import { Blog } from "../components/Blog"

const graphCms = new GraphQLClient(
	`https://api-ap-south-1.hygraph.com/v2/${process.env.API_KEY}/master`
)

const QUERY = gql`
	{
		posts {
			id {
				title
				publishedDate
				slug
				content {
					html
				}
				author {
					name
					authorPhoto {
						url
					}
				}
				coverPhoto {
						url
					}
				}
			}
		}
	}
`
async function getServerSideProps() {
	const { posts } = await graphCms.request(QUERY)
	return {
		props: {
			posts
		}
	}
}

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Bloggy</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.svg' />
			</Head>

			<main className={styles.main}>
				{posts.map((post) => (
					<Blog
						title={post.title}
						author={post.author}
						coverPhoto={post.coverPhoto}
						key={post.id}
						publishedDate={post.publishedDate}
						slug={post.slug}
					/>
				))}
			</main>
		</div>
	)
}
